export {
  LOGIN,
  GET_USER_COURSES,
  GET_USER_INFO,
  GET_COURSE_INFO,
  GET_COURSE_ASSIGNMENTS,
} from "./queries";

export {
  UPDATE_COURSE_INFO,
  ADD_USER_TO_COURSE,
  UPDATE_USER_INFO,
  CREATE_COURSE,
} from "./mutations.js";
